export const blackFullPieceData = [
    {
        key: 1,
        id: "blackRook1",
        piece: "rook",
        colorPiece: "black",
    },
    {
        key: 2,
        id: "blackKnight1",
        piece: "knight",
        colorPiece: "black",
    },
    {
        key: 3,
        id: "blackBishop1",
        piece: "bishop",
        colorPiece: "black",
    },
    {
        key: 4,
        id: "blackQueen",
        piece: "queen",
        colorPiece: "black",
    },
    {
        key: 5,
        id: "blackKing",
        piece: "king",
        colorPiece: "black",
    },
    {
        key: 6,
        id: "blackBishop2",
        piece: "bishop",
        colorPiece: "black",
        enPassant: false,
    },
    {
        key: 7,
        id: "blackKnight2",
        piece: "knight",
        colorPiece: "black",
    },
    {
        key: 8,
        id: "blackRook2",
        piece: "rook",
        colorPiece: "black",
    },
];

export const blackFullPawnData = [
    {
        key: 1,
        id: "blackPawn1",
        piece: "pawn",
        colorPiece: "black",
        enPassant: false,
    },
    {
        key: 2,
        id: "blackPawn2",
        piece: "pawn",
        colorPiece: "black",
        enPassant: false,
    },
    {
        key: 3,
        id: "blackPawn3",
        piece: "pawn",
        colorPiece: "black",
        enPassant: false,
    },
    {
        key: 4,
        id: "blackPawn4",
        piece: "pawn",
        colorPiece: "black",
        enPassant: false,
    },
    {
        key: 5,
        id: "blackPawn5",
        piece: "pawn",
        colorPiece: "black",
        enPassant: false,
    },
    {
        key: 6,
        id: "blackPawn6",
        piece: "pawn",
        colorPiece: "black",
        enPassant: false,
    },
    {
        key: 7,
        id: "blackPawn7",
        piece: "pawn",
        colorPiece: "black",
        enPassant: false,
    },
    {
        key: 8,
        id: "blackPawn8",
        piece: "pawn",
        colorPiece: "black",
        enPassant: false,
    },
];

export const whiteFullPieceData = [
    {
        key: 1,
        id: "whiteRook1",
        piece: "rook",
        colorPiece: "white",
    },
    {
        key: 2,
        id: "whiteKnight1",
        piece: "knight",
        colorPiece: "white",
    },
    {
        key: 3,
        id: "whiteBishop1",
        piece: "bishop",
        colorPiece: "white",
    },
    {
        key: 4,
        id: "whiteQueen",
        piece: "queen",
        colorPiece: "white",
    },
    {
        key: 5,
        id: "whiteKing",
        piece: "king",
        colorPiece: "white",
    },
    {
        key: 6,
        id: "whiteBishop2",
        piece: "bishop",
        colorPiece: "white",
    },
    {
        key: 7,
        id: "whiteKnight2",
        piece: "knight",
        colorPiece: "white",
    },
    {
        key: 8,
        id: "whiteRook2",
        piece: "rook",
        colorPiece: "white",
    },
];

export const whiteFullPawnData = [
    {
        key: 1,
        id: "whitePawn1",
        piece: "pawn",
        colorPiece: "white",
        enPassant: false,
    },
    {
        key: 2,
        id: "whitePawn2",
        piece: "pawn",
        colorPiece: "white",
        enPassant: false,
    },
    {
        key: 3,
        id: "whitePawn3",
        piece: "pawn",
        colorPiece: "white",
        enPassant: false,
    },
    {
        key: 4,
        id: "whitePawn4",
        piece: "pawn",
        colorPiece: "white",
        enPassant: false,
    },
    {
        key: 5,
        id: "whitePawn5",
        piece: "pawn",
        colorPiece: "white",
        enPassant: false,
    },
    {
        key: 6,
        id: "whitePawn6",
        piece: "pawn",
        colorPiece: "white",
        enPassant: false,
    },
    {
        key: 7,
        id: "whitePawn7",
        piece: "pawn",
        colorPiece: "white",
        enPassant: false,
    },
    {
        key: 8,
        id: "whitePawn8",
        piece: "pawn",
        colorPiece: "white",
        enPassant: false,
    },
];
