export const blackFullPieceData = [
    {
        key: 1,
        id: "blackRook1",
        bottom: "bottom-8/8",
        left: "left-1/8",
        colorBox: "bg-white",
        piece: "rook",
        colorPiece: "black",
    },
    {
        key: 2,
        id: "blackKnight1",
        bottom: "bottom-8/8",
        left: "left-2/8",
        colorBox: "bg-blue-400",
        piece: "knight",
        colorPiece: "black",
    },
    {
        key: 3,
        id: "blackBishop1",
        bottom: "bottom-8/8",
        left: "left-3/8",
        colorBox: "bg-white",
        piece: "bishop",
        colorPiece: "black",
    },
    {
        key: 4,
        id: "blackKing",
        bottom: "bottom-8/8",
        left: "left-4/8",
        colorBox: "bg-blue-400",
        piece: "king",
        colorPiece: "black",
    },
    {
        key: 5,
        id: "blackQueen",
        bottom: "bottom-8/8",
        left: "left-5/8",
        colorBox: "bg-white",
        piece: "queen",
        colorPiece: "black",
    },
    {
        key: 6,
        id: "blackBishop2",
        bottom: "bottom-8/8",
        left: "left-6/8",
        colorBox: "bg-blue-400",
        piece: "bishop",
        colorPiece: "black",
    },
    {
        key: 7,
        id: "blackKnight2",
        bottom: "bottom-8/8",
        left: "left-7/8",
        colorBox: "bg-white",
        piece: "knight",
        colorPiece: "black",
    },
    {
        key: 8,
        id: "blackRook2",
        bottom: "bottom-8/8",
        left: "left-8/8",
        colorBox: "bg-blue-400",
        piece: "rook",
        colorPiece: "black",
    },
];

export const blackFullPawnData = [
    {
        key: 1,
        id: "blackPawn1",
        bottom: "bottom-7/8",
        left: "left-1/8",
        colorBox: "bg-blue-400",
        piece: "pawn",
        colorPiece: "black",
    },
    {
        key: 2,
        id: "blackPawn2",
        bottom: "bottom-7/8",
        left: "left-2/8",
        colorBox: "bg-white",
        piece: "pawn",
        colorPiece: "black",
    },
    {
        key: 3,
        id: "blackPawn3",
        bottom: "bottom-7/8",
        left: "left-3/8",
        colorBox: "bg-blue-400",
        piece: "pawn",
        colorPiece: "black",
    },
    {
        key: 4,
        id: "blackPawn4",
        bottom: "bottom-7/8",
        left: "left-4/8",
        colorBox: "bg-white",
        piece: "pawn",
        colorPiece: "black",
    },
    {
        key: 5,
        id: "blackPawn5",
        bottom: "bottom-7/8",
        left: "left-5/8",
        colorBox: "bg-blue-400",
        piece: "pawn",
        colorPiece: "black",
    },
    {
        key: 6,
        id: "blackPawn6",
        bottom: "bottom-7/8",
        left: "left-6/8",
        colorBox: "bg-white",
        piece: "pawn",
        colorPiece: "black",
    },
    {
        key: 7,
        id: "blackPawn7",
        bottom: "bottom-7/8",
        left: "left-7/8",
        colorBox: "bg-blue-400",
        piece: "pawn",
        colorPiece: "black",
    },
    {
        key: 8,
        id: "blackPawn8",
        bottom: "bottom-7/8",
        left: "left-8/8",
        colorBox: "bg-white",
        piece: "pawn",
        colorPiece: "black",
    },
];

export const whiteFullPieceData = [
    {
        key: 1,
        id: "whiteRook1",
        bottom: "bottom-1/8",
        left: "left-1/8",
        colorBox: "bg-blue-400",
        piece: "rook",
        colorPiece: "white",
    },
    {
        key: 2,
        id: "whiteKnight1",
        bottom: "bottom-1/8",
        left: "left-2/8",
        colorBox: "bg-white",
        piece: "knight",
        colorPiece: "white",
    },
    {
        key: 3,
        id: "whiteBishop1",
        bottom: "bottom-1/8",
        left: "left-3/8",
        colorBox: "bg-blue-400",
        piece: "bishop",
        colorPiece: "white",
    },
    {
        key: 4,
        id: "whiteKing",
        bottom: "bottom-1/8",
        left: "left-4/8",
        colorBox: "bg-white",
        piece: "king",
        colorPiece: "white",
    },
    {
        key: 5,
        id: "whiteQueen",
        bottom: "bottom-1/8",
        left: "left-5/8",
        colorBox: "bg-blue-400",
        piece: "queen",
        colorPiece: "white",
    },
    {
        key: 6,
        id: "whiteBishop2",
        bottom: "bottom-1/8",
        left: "left-6/8",
        colorBox: "bg-white",
        piece: "bishop",
        colorPiece: "white",
    },
    {
        key: 7,
        id: "whiteKnight2",
        bottom: "bottom-1/8",
        left: "left-7/8",
        colorBox: "bg-blue-400",
        piece: "knight",
        colorPiece: "white",
    },
    {
        key: 8,
        id: "whiteRook2",
        bottom: "bottom-1/8",
        left: "left-8/8",
        colorBox: "bg-white",
        piece: "rook",
        colorPiece: "white",
    },
];

export const whiteFullPawnData = [
    {
        key: 1,
        id: "whitePawn1",
        bottom: "bottom-2/8",
        left: "left-1/8",
        colorBox: "bg-white",
        piece: "pawn",
        colorPiece: "white",
    },
    {
        key: 2,
        id: "whitePawn2",
        bottom: "bottom-2/8",
        left: "left-2/8",
        colorBox: "bg-blue-400",
        piece: "pawn",
        colorPiece: "white",
    },
    {
        key: 3,
        id: "whitePawn3",
        bottom: "bottom-2/8",
        left: "left-3/8",
        colorBox: "bg-white",
        piece: "pawn",
        colorPiece: "white",
    },
    {
        key: 4,
        id: "whitePawn4",
        bottom: "bottom-2/8",
        left: "left-4/8",
        colorBox: "bg-blue-400",
        piece: "pawn",
        colorPiece: "white",
    },
    {
        key: 5,
        id: "whitePawn5",
        bottom: "bottom-2/8",
        left: "left-5/8",
        colorBox: "bg-white",
        piece: "pawn",
        colorPiece: "white",
    },
    {
        key: 6,
        id: "whitePawn6",
        bottom: "bottom-2/8",
        left: "left-6/8",
        colorBox: "bg-blue-400",
        piece: "pawn",
        colorPiece: "white",
    },
    {
        key: 7,
        id: "whitePawn7",
        bottom: "bottom-2/8",
        left: "left-7/8",
        colorBox: "bg-white",
        piece: "pawn",
        colorPiece: "white",
    },
    {
        key: 8,
        id: "whitePawn8",
        bottom: "bottom-2/8",
        left: "left-8/8",
        colorBox: "bg-blue-400",
        piece: "pawn",
        colorPiece: "white",
    },
];
